export const USER_LOGGED_IN = 'USER_LOGGED_IN';
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const PRODUCTS_FETCHED = 'PRODUCTS_FETCHED';
export const PRODUCT_CREATED = 'PRODUCT_CREATED';
export const PRODUCT_DELETED = 'PRODUCT_DELETED';